### ISSUE TITLE
docker-compose 指定Dockerfile 路径出错

### ISSUE THREAD

**Issue by weiyi88** [EHEWON/ezwork-ai-doc-translation#1]
使用docker-compose 启动时候报错：
```
ezwork-ai-doc-translation git:(main) ✗ docker-compose -p dos-translate up -d
[+] Building 0.0s (1/1) FINISHED docker:desktop-linux
=> [php internal] load build definition from Dockerfile 0.0s
=> => transferring dockerfile: 2B 0.0s
failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
```

原因是：docker-compose 文件中，指代 Dockerfile 路径时候不对。如图：
<img width="1388" alt="image" src="https://github.com/user-attachments/assets/8b96a0de-a65c-4c4d-ae1d-8ef8b4bb522a">
这上下文j路径有问题

ps：这Dockerfile 有很大优化空间，RUN 命令的可以写成一条， 减少层数，还有，可以先build 完后推送镜像，不用每次都install ，很慢的

**Comment by EHEWON** [comment]
api目录应该是php的代码结构，但看截图是前端的
[submodule "api"]
	path = api
	url = https://github.com/EHEWON/ezwork-api.git

**Comment by EHEWON** [comment]
这提议很好，回头将推送完整的镜像，不需要每次都build了
