### ISSUE TITLE
提示找不到文件：docker.env

### ISSUE THREAD

**Issue by fandong1993** [EHEWON/ezwork-ai-doc-translation#10]
36
#8 [php 4/6] COPY docker.env /var/www/ezwork/.env
37
#8 ERROR: failed to calculate checksum of ref 91d49cb2-3496-449a-9a7b-0a1445fd9925::mi2jt8kiwwlqqgahyuqi7yljm: "/docker.env": not found

**Comment by EHEWON** [comment]
修复了一处错误，请重新更新下api代码
cd api
git checkout master
git pull
再执行docker-composer构建
