### ISSUE TITLE
启动后 network 报错

### ISSUE THREAD

**Issue by weiyi88** [EHEWON/ezwork-ai-doc-translation#2]
<img width="1326" alt="image" src="https://github.com/user-attachments/assets/645a811a-b110-43c1-87dc-dfa341e9c6f9">

老哥，就不替你调试bug了。有这情况。要不你弄个web demo 试用看看

**Comment by EHEWON** [comment]
接口地址定义的是http://localhost:3000, 这里怎么变成3010端口了?

**Comment by weiyi88** [comment]
额，3000有其他服务。都用docker network 可以用容器互通的

**Comment by EHEWON** [comment]
![image](https://github.com/user-attachments/assets/6671e64c-6221-465a-8d71-2b2f82b6793d)

前端定义的是3000端口， 根据部署及配置文件， api应该也是3000。
如果3000被占用， 那前端也应该是3010才对
如果要改变端口，需要改以下地方：
docker-compose.yml app项的端口改成3010
frontend.env 和 admin.env 接口地址也改成3010

**Comment by weiyi88** [comment]
好的，我按照 ReadMe 再试试
