### ISSUE TITLE
接口错误

### ISSUE THREAD

**Issue by weiyi88** [EHEWON/ezwork-ai-doc-translation#3]
<img width="1331" alt="image" src="https://github.com/user-attachments/assets/90ac12fb-b71f-4156-9f90-941ff2f38023">

按照readme 来操作的，无力吐槽了

**Comment by EHEWON** [comment]
谢谢反馈，我们正在检查问题，预计下周会发布更新，请耐心等待。

**Comment by EHEWON** [comment]
我们更新使用了新的api镜像,构建速度更快了
建议将之前的镜像,volumes和代码删除重新来一遍
