### ISSUE TITLE
502接口错误

### ISSUE THREAD

**Issue by ttbush** [EHEWON/ezwork-ai-doc-translation#5]
<img width="1257" alt="image" src="https://github.com/user-attachments/assets/ef8596ac-7433-450e-a08e-7f256d5d636f">
<img width="888" alt="image" src="https://github.com/user-attachments/assets/2cb39478-96f1-4375-ad55-56ffdebd6f4e">
<img width="873" alt="image" src="https://github.com/user-attachments/assets/61befd8f-5cb1-4691-8dea-6bf416917a55">

**Comment by EHEWON** [comment]
docker是不是api服务没有跑起来？

**Comment by ttbush** [comment]
能看到这个服务，我是本地localhost，那几个配置文件就没怎么改，是不是配置文件里要改哪些地方呀

<img width="586" alt="image" src="https://github.com/user-attachments/assets/c789d1b5-76c9-4748-8667-ce9ed8c81ac2">
