### ISSUE TITLE
部署无法运行

### ISSUE THREAD

**Issue by ttbush** [EHEWON/ezwork-ai-doc-translation#6]
Hi 部署过程中遇到几个问题，第一个是部署时候提示docker文件找不到：
<img width="1102" alt="image" src="https://github.com/user-attachments/assets/67efb0ba-3918-43ca-aee8-46da78e609f0">
然后我g改了这里面的./api/改到改成根目录能部署成功了

然后实际，走到api安装插件的时候，提示docker中bash命令不存在，装了bash之后，运行docker exec -it  ezwork_api bash
apt install libreoffice unoconv，提示无法安装unoconv，然后通过装python走，虚拟环境装了，提示缺少 distutils 模块，继续安装setuptools，终于都装好了。然后访问，还是502接口不通。

**Comment by ttbush** [comment]
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/042d652b-5710-4212-967b-9792d75bb1c0">
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/3764d966-64a0-4a55-861e-baa5092a2d3e">

**Comment by EHEWON** [comment]
好的，我们尽快处理，谢谢反馈。

**Comment by EHEWON** [comment]
是否更新了最新的代码？
如果一开始没找到dockerfile, 可以手动执行下以下命令更新
cd api
git checkout master
git pull

**Comment by ttbush** [comment]
拉了最新代码，
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/83739da7-8bf3-4dc9-a059-a03d974be84e">
这次500报错，看起来mysql好像有问题{
    "message": "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ezwork.setting' doesn't exist (Connection: mysql, SQL: select alias,value,serialized from `setting` where `group` = api_setting)",
    "exception": "Illuminate\\Database\\QueryException",
    "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
    "line": 813,
    "trace": [
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
            "line": 767,
            "function": "runQueryCallback",
            "class": "Illuminate\\Database\\Connection",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
            "line": 398,
            "function": "run",
            "class": "Illuminate\\Database\\Connection",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php",
            "line": 2898,
            "function": "select",
            "class": "Illuminate\\Database\\Connection",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php",
            "line": 2883,
            "function": "runSelect",
            "class": "Illuminate\\Database\\Query\\Builder",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php",
            "line": 3467,
            "function": "Illuminate\\Database\\Query\\{closure}",
            "class": "Illuminate\\Database\\Query\\Builder",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php",
            "line": 2882,
            "function": "onceWithColumns",
            "class": "Illuminate\\Database\\Query\\Builder",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php",
            "line": 738,
            "function": "get",
            "class": "Illuminate\\Database\\Query\\Builder",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php",
            "line": 722,
            "function": "getModels",
            "class": "Illuminate\\Database\\Eloquent\\Builder",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/app/Models/Setting.php",
            "line": 45,
            "function": "get",
            "class": "Illuminate\\Database\\Eloquent\\Builder",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/app/Http/Controllers/Api/TranslateController.php",
            "line": 95,
            "function": "getSettingByGroup",
            "class": "App\\Models\\Setting",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
            "line": 54,
            "function": "setting",
            "class": "App\\Http\\Controllers\\Api\\TranslateController",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
            "line": 43,
            "function": "callAction",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 260,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 206,
            "function": "runController",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 806,
            "function": "run",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 144,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php",
            "line": 50,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 119,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 805,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 784,
            "function": "runRouteWithinStack",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 748,
            "function": "runRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 737,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 200,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 144,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/app/Http/Middleware/HandleCors.php",
            "line": 22,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "App\\Http\\Middleware\\HandleCors",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 119,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 175,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 144,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/vendor/laravel/framework/src/Illuminate/Foundation/Application.php",
            "line": 1168,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/var/www/ezwork/public/index.php",
            "line": 19,
            "function": "handleRequest",
            "class": "Illuminate\\Foundation\\Application",
            "type": "->"
        }
    ]
}

**Comment by ttbush** [comment]
> 好的，我们尽快处理，谢谢反馈。
<img width="988" alt="image" src="https://github.com/user-attachments/assets/76198aa6-e1b7-45eb-ab97-e35a5042f6ba">

看了下这个表，数据库里确实不存在

**Comment by EHEWON** [comment]
主库不是最新的代码，可以更新下代码，看下init.sql. 里面应该有定义的。可以手动更新下表

**Comment by ttbush** [comment]
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/029804e3-05e5-4c2d-8023-ddf0f618d010">
跑起来了，还是有报错，我重新拉了代码，数据库还是有问题的

**Comment by EHEWON** [comment]
有个php扩展没装
在项目根目录下执行下
docker-compose exec php docker-php-ext-install bcmath

**Comment by ttbush** [comment]
我看了下表里确实没有'origin_lang' 这个字段

**Comment by EHEWON** [comment]
alter table translate add origin_lang varchar(255);

**Comment by ttbush** [comment]
<img width="717" alt="image" src="https://github.com/user-attachments/assets/4a7ac16d-214d-415f-ab35-8d5c50c1e9e9">
运行起来了，这里检测也通过了。
但是点立即翻译之后，f12看到一只在process 重复很多个，然后页面上没动静了，
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/9192e94d-ca94-4271-9e10-6791a2b0a691">
返回请求
<img width="1031" alt="image" src="https://github.com/user-attachments/assets/bd0b9bac-586f-4bcb-a142-589e13ed4c49">

**Comment by ttbush** [comment]
<img width="662" alt="image" src="https://github.com/user-attachments/assets/d88ac9ba-f647-4074-b217-50792e0711c4">
一直停在翻译中没继续

**Comment by EHEWON** [comment]
直接使用openai的接口应该是不行的，对国内是屏蔽的，建议选择其他的中转服务

**Comment by ttbush** [comment]
我的服务器在海外的，接口校验是通的

**Comment by ttbush** [comment]
![Uploading image.png…]()
我F12看了openai端口是通的，但是传上去文件， 翻译进度为0

**Comment by ttbush** [comment]
也没报错了
![Uploading image.png…]()

**Comment by ttbush** [comment]
<img width="1383" alt="image" src="https://github.com/user-attachments/assets/918d3c40-fb57-48f7-bbdb-444ce2f70795">

**Comment by ttbush** [comment]
<img width="593" alt="image" src="https://github.com/user-attachments/assets/a57726a3-490d-460f-8fee-b1d627a7ecc3">
<img width="1017" alt="image" src="https://github.com/user-attachments/assets/2e06a4da-c8a6-41f6-9657-42f3aa77a786">

**Comment by ttbush** [comment]
方便加个联系方式，帮忙看一下么。官网那个demo环境，需要注册，试不了效果

**Comment by EHEWON** [comment]
加微信吧 tvrc4m
