### ISSUE TITLE
502错误

### ISSUE THREAD

**Issue by passengeryjy** [EHEWON/ezwork-ai-doc-translation#8]
ubuntu下，非docker部署，php8.2-fpm+nginx，出现502错误。
![image](https://github.com/user-attachments/assets/8db968ca-a66f-4b1c-95d1-fdc743975dfc)

**Comment by EHEWON** [comment]
php出问题了，建议加微信群详细说
![image](https://github.com/user-attachments/assets/eb3e8af5-c8d3-41b2-814b-6c9dd1a1f56b)

**Comment by liuxiao-0371** [comment]
微信二维码已过期。
